[package]
name = "snake-egg"
version = "0.1.0"
edition = "2021"

[lib]
name = "snake_egg"
crate-type = ["cdylib"]

[dependencies]
hashbrown = "0.11"
once_cell = "1"
pyo3 = { version = "0.15", features = ["extension-module"] }
egg = { git = "https://github.com/oflatt/egg", rev = "a97a94c831c067847855c0f1de1a8cff9920903d" }